---
- hosts: all
  sudo: yes
  tasks:
    - name: apt update
      apt: update_cache=yes
    - name: upgrade all packages
      apt: upgrade=dist
    - name: install required package
      apt: pkg={{item}}
      with_items:
        - screen
        - apache2
        - mysql-server-5.5
        - php5
        - php5-dev
        - php-pear
        - php-apc
        - php5-mysql
        - php5-gd
        - php5-curl
        - language-pack-ja
        - postfix
        - mailutils
      tags: package
    - name: copy screen.rc
      copy: src=files/home/vagrant/.screenrc dest=/home/vagrant/.screenrc owner=vagrant mode=0644
      sudo: no
    - name: copy screen.rc
      copy: src=files/etc/postfix/main.cf dest=/etc/postfix/main.cf
#    - name: check VBoxGuestAdditions version
#      shell: "[ -d /opt/VBoxGuestAdditions-4.3.10/ ] && echo 1"
#      register: shell_result
#    - name: symlink to VBoxGuestAdditions
#      file: src=/opt/VBoxGuestAdditions-4.3.10/lib/VBoxGuestAdditions dest=/usr/lib/VBoxGuestAdditions state=link
#      when: shell_result.stdout.endswith("1")
      # php related
    - name: set apc enabled
      lineinfile: dest=/etc/php5/mods-available/apc.ini insertafter=EOF line="apc.rfc1867 = 1"
      tags: php      
      # mysql related functions
    - name: install ansible related libraries
      apt: pkg={{item}}
      with_items:
        - python-mysqldb
      tags: mysql
    - name: create mysql db
      mysql_db: name=drupal
      tags: mysql
    - name: create mysql user
      mysql_user: name=drupal password=drupal priv="drupal.*:SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES"
      tags: mysql
      # apache related functions
    - name: copy drupal apache setting
      copy: src=files/etc/apache2/sites-available/drupal dest=/etc/apache2/sites-available/drupal mode=0644
      tags: apache
    - name: disable default site setting
      shell: a2dissite default
      tags: apache
    - name: enable drupal site setting
      shell: a2ensite drupal
      tags: apache
    - name: enable apache2
      service: name=apache2 state=started enabled=yes
      tags: apache
